AWSTemplateFormatVersion: "2010-09-09"
Description: A Cloud9 Environment for Basic Development
  
Parameters:
  EC2InstanceType:
    Default: t2.medium
    Description: EC2 instance type on which IDE runs
    Type: String
  AutoHibernateTimeout:
    Default: 30
    Description: How many minutes idle before shutting down the IDE
    Type: Number
  SubnetIdentifier:
    Description: SubnetId
    Type: AWS::EC2::Subnet::Id
Resources:
  C9Environment:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      Repositories:
      - RepositoryUrl: https://github.com/mkoelle/cloud9-resources.git
        PathComponent: github.com/mkoelle/cloud9-resources
      Description: Cloud9 IDE
      AutomaticStopTimeMinutes:
        Ref: AutoHibernateTimeout
      SubnetId:
        Ref: SubnetIdentifier
      InstanceType:
        Ref: EC2InstanceType
      Name:
        Ref: AWS::StackName
Outputs:
  Cloud9URL:
    Value:
      Fn::Join:
      - ''
      - - https://console.aws.amazon.com/cloud9/home/environments/
        - Ref: C9Environment
    Description: Cloud9 environment
